/**
 * tools/index.ts — 把所有 tool 註冊函式掛到同一個 McpServer 實例。
 * 純聚合層，不放任何業務邏輯。
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerLoginTool } from './login.ts';
import { registerGetAgentPhoneNumberVisibilityTool } from './get_agent_phone_number_visibility.ts';
import { registerViewAgentPhoneNumberTool } from './view_agent_phone_number.ts';
import { registerListAgentReportsTool } from './list_agent_reports.ts';
import { registerListAgentReportDetailsTool } from './list_agent_report_details.ts';
import { registerGetAgentReportStatisticsTool } from './get_agent_report_statistics.ts';
import { registerListAgentGameReportsTool } from './list_agent_game_reports.ts';
import { registerListAgentBetRecordsTool } from './list_agent_bet_records.ts';
import { registerListAgentMemberGameReportsTool } from './list_agent_member_game_reports.ts';
import { registerListAgentLoginHistoriesTool } from './list_agent_login_histories.ts';
import { registerListAgentReferralDomainsTool } from './list_agent_referral_domains.ts';
import { registerGetDailyPaymentHighNetWorthStatisticsTool } from './get_daily_payment_high_net_worth_statistics.ts';
import { registerGetDailyPaymentHighNetWorthUsersTool } from './get_daily_payment_high_net_worth_users.ts';
import { registerGetDailyUserGameVendorTagBetSummaryTool } from './get_daily_user_game_vendor_tag_bet_summary.ts';
import { registerGetDailyUserGameVendorTagBetUserSummaryTool } from './get_daily_user_game_vendor_tag_bet_user_summary.ts';
import { registerGetTodayPlatformStatisticTool } from './get_today_platform_statistic.ts';
import { registerGetYesterdayPlatformStatisticTool } from './get_yesterday_platform_statistic.ts';
import { registerListDailyVipStatisticsTool } from './list_daily_vip_statistics.ts';
import { registerListDepositMethodStatisticsTool } from './list_deposit_method_statistics.ts';
import { registerListDepositDailyReportTool } from './list_deposit_daily_report.ts';
import { registerListDepositWithdrawDailyReportTool } from './list_deposit_withdraw_daily_report.ts';
import { registerListGameVendorsTool } from './list_game_vendors.ts';
import { registerListVendorGamesTool } from './list_vendor_games.ts';
import { registerOnboardVendorGameTool } from './onboard_vendor_game.ts';
import { registerGetMessageBoardSettingTool } from './get_message_board_setting.ts';
import { registerUpdateMessageBoardSettingTool } from './update_message_board_setting.ts';
import { registerGetMessageBoardPostsTool } from './get_message_board_posts.ts';
import { registerGetPostCommentsTool } from './get_post_comments.ts';
import { registerGetPostGiftRecordsTool } from './get_post_gift_records.ts';
import { registerGetMessageBoardCommentsTool } from './get_message_board_comments.ts';
import { registerReviewPostTool } from './review_post.ts';
import { registerBatchReviewPostsTool } from './batch_review_posts.ts';
import { registerDelistPostTool } from './delist_post.ts';
import { registerRelistPostTool } from './relist_post.ts';
import { registerSetIsPinnedPostTool } from './set_is_pinned_post.ts';
import { registerRemovePostTool } from './remove_post.ts';
import { registerGetGameLocalizationsTool } from './get_game_localizations.ts';
import { registerListTwoEightGamesTool } from './list_two_eight_games.ts';
import { registerListInHouseVendorsTool } from './list_in_house_vendors.ts';
import { registerGetGameVendorTool } from './get_game_vendor.ts';
import { registerUpdateGameVendorTool } from './update_game_vendor.ts';
import { registerResolveInHousePlayGroupGameIdsTool } from './resolve_in_house_play_group_game_ids.ts';
import { registerUpdateGameVendorStatusTool } from './update_game_vendor_status.ts';
import { registerGetActivityTabsTool } from './get_activity_tabs.ts';
import { registerCreateOrUpdateActivityTabTool } from './create_or_update_activity_tab.ts';
import { registerToggleActivityTabTool } from './toggle_activity_tab.ts';
import { registerGetActivityConfigsTool } from './get_activity_configs.ts';
import { registerGetUserIdByIdentifierTool } from './get_user_id_by_identifier.ts';
import { registerGetFissionActivityOptionsTool } from './get_fission_activity_options.ts';
import { registerListHomePagePopupsTool } from './list_home_page_popups.ts';
import { registerCreateHomePagePopupTool } from './create_home_page_popup.ts';
import { registerSetHomePagePopupStatusTool } from './set_home_page_popup_status.ts';
import { registerEditHomePagePopupTool } from './edit_home_page_popup.ts';
import { registerListHomePagePopupFissionActivitiesTool } from './list_home_page_popup_fission_activities.ts';
import { registerListFloatingWindowsTool } from './list_floating_windows.ts';
import { registerCreateFloatingWindowTool } from './create_floating_window.ts';
import { registerUpdateRoomSortOrderTool } from './update_room_sort_order.ts';
import { registerGetMuteHistoryTool } from './get_mute_history.ts';
import { registerCreateOrUpdateRoomMuteTool } from './create_or_update_room_mute.ts';
import { registerUpdateGameVendorMaintenanceStatusTool } from './update_game_vendor_maintenance_status.ts';
import { registerUpdateGameVendorGameStatusTool } from './update_game_vendor_game_status.ts';
import { registerListAllBrandsTool } from './list_all_brands.ts';
import { registerGetBrandForEditTool } from './get_brand_for_edit.ts';
import { registerUpdateBrandStatusTool } from './update_brand_status.ts';
import { registerListAllGameDisplayTagsTool } from './list_all_game_display_tags.ts';
import { registerUpdateGameTagStatusTool } from './update_game_tag_status.ts';
import { registerUpdateGameTagSortOrderTool } from './update_game_tag_sort_order.ts';
import { registerCreateOrUpdateGameDisplayTagTool } from './create_or_update_game_display_tag.ts';
import { registerListCustomerCategoryDetailsTool } from './list_customer_category_details.ts';
import { registerUpdateCustomerCategorySortOrderTool } from './update_customer_category_sort_order.ts';
import { registerUpdateCustomerCategoryStatusTool } from './update_customer_category_status.ts';
import { registerGetCustomerConfigRestrictTool } from './get_customer_config_restrict.ts';
import { registerSetCustomerConfigRestrictTool } from './set_customer_config_restrict.ts';
import { registerGetCustomerTicketsTool } from './get_customer_tickets.ts';
import { registerCreateOrUpdateItemTool } from './create_or_update_item.ts';
import { registerListItemsTool } from './list_items.ts';
import { registerListEnabledItemsAllTool } from './list_enabled_items_all.ts';
import { registerGetItemNamesByIdTool } from './get_item_names_by_id.ts';
import { registerUpdateItemStatusTool } from './update_item_status.ts';
import { registerListRoomsTool } from './list_rooms.ts';
import { registerGetRoomNamesTool } from './get_room_names.ts';
import { registerGetRoomAnnouncementsTool } from './get_room_announcements.ts';
import { registerGetRoomMembersTool } from './get_room_members.ts';
import { registerGetMutedRoomMembersTool } from './get_muted_room_members.ts';
import { registerKickRoomMemberTool } from './kick_room_member.ts';
import { registerMuteRoomMemberTool } from './mute_room_member.ts';
import { registerUnmuteRoomMemberTool } from './unmute_room_member.ts';
import { registerGetRoomChatHistoryTool } from './get_room_chat_history.ts';
import { registerGetRoomChatRecordsTool } from './get_room_chat_records.ts';
import { registerGetRoomShowOrderRecordsTool } from './get_room_show_order_records.ts';
import { registerGetRoomMonitorListTool } from './get_room_monitor_list.ts';
import { registerGetRoomMuteListTool } from './get_room_mute_list.ts';
import { registerGetPlatformModulesTool } from './get_platform_modules.ts';
import { registerListPointTransactionsTool } from './list_point_transactions.ts';
import { registerListAppUserTotalPointsTool } from './list_app_user_total_points.ts';
import { registerListVipPointSettingsTool } from './list_vip_point_settings.ts';
import { registerGetPointSettingTool } from './get_point_setting.ts';
import { registerUpdatePointSettingTool } from './update_point_setting.ts';
import { registerGetVipPointSettingTool } from './get_vip_point_setting.ts';
import { registerUpdateVipPointSettingTool } from './update_vip_point_setting.ts';
import { registerGetPointSignInSettingTool } from './get_point_sign_in_setting.ts';
import { registerUpdatePointSignInSettingTool } from './update_point_sign_in_setting.ts';
import { registerGetPointHolidaySettingTool } from './get_point_holiday_setting.ts';
import { registerUpdatePointHolidayStatusTool } from './update_point_holiday_status.ts';
import { registerCreateOrUpdatePointHolidayBonusTool } from './create_or_update_point_holiday_bonus.ts';
import { registerDeletePointHolidayBonusTool } from './delete_point_holiday_bonus.ts';
import { registerGetVipSettingEquityIconsTool } from './get_vip_setting_equity_icons.ts';
import { registerGetVipLevelSettingsTool } from './get_vip_level_settings.ts';
import { registerDeleteVipLevelSettingTool } from './delete_vip_level_setting.ts';
import { registerGetVipSettingTool } from './get_vip_setting.ts';
import { registerUpdateVipSettingTool } from './update_vip_setting.ts';
import { registerGetChatSpeechSettingTool } from './get_chat_speech_setting.ts';
import { registerUpdateChatSpeechSettingTool } from './update_chat_speech_setting.ts';
import { registerGetPlatformVerificationConfigTool } from './get_platform_verification_config.ts';
import { registerUpdatePlatformVerificationCaptchaTypeTool } from './update_platform_verification_captcha_type.ts';
import { registerListInformationConfigsTool } from './list_information_configs.ts';
import { registerGetInformationReadCountTool } from './get_information_read_count.ts';
import { registerCreateUrgentInfoConfigTool } from './create_urgent_info_config.ts';
import { registerListPlatformRiskStrategiesTool } from './list_platform_risk_strategies.ts';
import { registerGetPlatformRiskStrategiesTool } from './get_platform_risk_strategies.ts';
import { registerGetPlatformRiskStrategyForEditTool } from './get_platform_risk_strategy_for_edit.ts';
import { registerUpdatePlatformRiskStrategyStatusTool } from './update_platform_risk_strategy_status.ts';
import { registerListPlatformRiskEventsTool } from './list_platform_risk_events.ts';
import { registerGetIpRegionListTool } from './get_ip_region_list.ts';
import { registerCreateOrUpdateIpRegionTool } from './create_or_update_ip_region.ts';
import { registerUpdateIpRegionStatusTool } from './update_ip_region_status.ts';
import { registerBatchUpdateIpRegionStatusTool } from './batch_update_ip_region_status.ts';
import { registerDeleteIpRegionTool } from './delete_ip_region.ts';
import { registerBatchDeleteIpRegionTool } from './batch_delete_ip_region.ts';
import { registerGetInHouseVendorListTool } from './get_in_house_vendor_list.ts';
import { registerGetInHousePlayGroupListTool } from './get_in_house_play_group_list.ts';
import { registerGetShowCategoryTool } from './get_show_category.ts';
import { registerUpdateShowCategoryTool } from './update_show_category.ts';
import { registerListClassificationCategoriesTool } from './list_classification_categories.ts';
import { registerCreateOrUpdateClassificationTool } from './create_or_update_classification.ts';
import { registerDeleteClassificationTool } from './delete_classification.ts';
import { registerGetCategoriesByClassificationTool } from './get_categories_by_classification.ts';
import { registerListUserTransactionsTool } from './list_user_transactions.ts';
import { registerGetAuditLogsTool } from './get_audit_logs.ts';
import { registerListRoomGiftsTool } from './list_room_gifts.ts';
import { registerGetRoomGiftStatisticSummaryTool } from './get_room_gift_statistic_summary.ts';
import { registerListRecordsTool } from './list_records.ts';
import { registerGetAnchorStatisticSummaryTool } from './get_anchor_statistic_summary.ts';
import { registerGetPlatformStatisticSummaryTool } from './get_platform_statistic_summary.ts';
import { registerGetCurrenciesTool } from './get_currencies.ts';
import { registerUpdateCurrencyStatusTool } from './update_currency_status.ts';
import { registerGetOtpSmsSettingsTool } from './get_otp_sms_settings.ts';
import { registerUpdateOtpSmsSettingsTool } from './update_otp_sms_settings.ts';
import { registerGetRegistrationIpQuotaConfigTool } from './get_registration_ip_quota_config.ts';
import { registerUpdateRegistrationIpQuotaConfigTool } from './update_registration_ip_quota_config.ts';
import { registerListRegistrationIpQuotasTool } from './list_registration_ip_quotas.ts';
import { registerExportRegistrationIpQuotasTool } from './export_registration_ip_quotas.ts';
import { registerToggleRegistrationIpQuotaStatusTool } from './toggle_registration_ip_quota_status.ts';
import { registerReleaseRegistrationIpQuotaTool } from './release_registration_ip_quota.ts';
import { registerListRegistrationIpUsersTool } from './list_registration_ip_users.ts';
import { registerGetUserEnterHistoryAppDomainsTool } from './get_user_enter_history_app_domains.ts';
import { registerGetUserEnterHistoryDomainReportTool } from './get_user_enter_history_domain_report.ts';
import { registerGetUserEnterHistoryDeviceReportTool } from './get_user_enter_history_device_report.ts';
import { registerGetRegistrationFieldConfigsTool } from './get_registration_field_configs.ts';
import { registerCreateOrUpdateRegistrationFieldConfigTool } from './create_or_update_registration_field_config.ts';
import { registerGetRegistrationLimitConfigTool } from './get_registration_limit_config.ts';
import { registerUpdateRegistrationLimitConfigTool } from './update_registration_limit_config.ts';
import { registerGetLoginRulesTool } from './get_login_rules.ts';
import { registerUpdateLoginPromptConfigTool } from './update_login_prompt_config.ts';
import { registerUpdateLoginVerificationConfigTool } from './update_login_verification_config.ts';
import { registerUpdatePasswordResetConfigTool } from './update_password_reset_config.ts';
import { registerListTradePasswordLockRecordTool } from './list_trade_password_lock_record.ts';
import { registerUnlockTradePasswordLockRecordTool } from './unlock_trade_password_lock_record.ts';
import { registerGetTradePasswordLockConfigTool } from './get_trade_password_lock_config.ts';
import { registerCreateOrUpdateTradePasswordLockConfigTool } from './create_or_update_trade_password_lock_config.ts';
import { registerGetFreezeConfigTool } from './get_freeze_config.ts';
import { registerUpdateFreezeConfigTool } from './update_freeze_config.ts';
import { registerGetSupportedLanguagesTool } from './get_supported_languages.ts';
import { registerGetTimezoneTool } from './get_timezone.ts';
import { registerGetPlatformCodeTool } from './get_platform_code.ts';
import { registerListUsersTool } from './list_users.ts';
import { registerUpdateUserStatusTool } from './update_user_status.ts';
import { registerListPlatformSupportedLanguagesTool } from './list_platform_supported_languages.ts';
import { registerCreateOrUpdateSupportLanguageTool } from './create_or_update_support_language.ts';
import { registerGetBackofficeSupportedLanguagesTool } from './get_backoffice_supported_languages.ts';
import { registerToggleBackofficeLanguageStatusTool } from './toggle_backoffice_language_status.ts';
import { registerSetBackofficeDefaultLanguageTool } from './set_backoffice_default_language.ts';
import { registerGetPlatformIdRolesTool } from './get_platform_id_roles.ts';
import { registerNewUserTool } from './new_user.ts';
import { registerListActivityRankingSettingsTool } from './list_activity_ranking_settings.ts';
import { registerGetPlatformRankingActivityListTool } from './get_platform_ranking_activity_list.ts';
import { registerChangeActivityRankingSettingStatusTool } from './change_activity_ranking_setting_status.ts';
import { registerCreateOrUpdateActivityRankingSettingTool } from './create_or_update_activity_ranking_setting.ts';
import { registerListFixedRankingSettingsTool } from './list_fixed_ranking_settings.ts';
import { registerChangeFixedRankingStatusTool } from './change_fixed_ranking_status.ts';
import { registerUpdateFixedRankingSettingTool } from './update_fixed_ranking_setting.ts';
import { registerListFixedRankingEntriesTool } from './list_fixed_ranking_entries.ts';
import { registerGetRouletteConfigNameListTool } from './get_roulette_config_name_list.ts';
import { registerGetRouletteConfigListTool } from './get_roulette_config_list.ts';
import { registerGetRouletteConfigByIdTool } from './get_roulette_config_by_id.ts';
import { registerSwitchRouletteConfigStatusTool } from './switch_roulette_config_status.ts';
import { registerGetRouletteRewardListTool } from './get_roulette_reward_list.ts';
import { registerGetRouletteRewardByIdTool } from './get_roulette_reward_by_id.ts';
import { registerGetRouletteRecordListTool } from './get_roulette_record_list.ts';
import { registerCreateOrUpdateRouletteConfigTool } from './create_or_update_roulette_config.ts';
import { registerCreateOrUpdateRouletteRewardTool } from './create_or_update_roulette_reward.ts';
import { registerGetSensitiveWordsTool } from './get_sensitive_words.ts';
import { registerCreateOrUpdateSensitiveWordTool } from './create_or_update_sensitive_word.ts';
import { registerBatchRemoveSensitiveWordTool } from './batch_remove_sensitive_word.ts';
import { registerGetRouletteRewardNameListTool } from './get_roulette_reward_name_list.ts';
import { registerGetLiveTabsTool } from './get_live_tabs.ts';
import { registerCreateOrUpdateLiveTabTool } from './create_or_update_live_tab.ts';
import { registerUpdateLiveTabStatusTool } from './update_live_tab_status.ts';
import { registerGetLiveCategoriesTool } from './get_live_categories.ts';
import { registerCreateOrUpdateLiveCategoryTool } from './create_or_update_live_category.ts';
import { registerUpdateLiveCategoryStatusTool } from './update_live_category_status.ts';
import { registerGetMerchantListTool } from './get_merchant_list.ts';
import { registerToggleMerchantStatusTool } from './toggle_merchant_status.ts';
import { registerGetMerchantSettingTool } from './get_merchant_setting.ts';
import { registerEditMerchantSettingTool } from './edit_merchant_setting.ts';
import { registerListAppGroupsTool } from './list_app_groups.ts';
import { registerListAppsTool } from './list_apps.ts';
import { registerUpdateAppTool } from './update_app.ts';
import { registerListAppVersionsTool } from './list_app_versions.ts';
import { registerGetAppVersionForEditTool } from './get_app_version_for_edit.ts';
import { registerListDownloadLinksTool } from './list_download_links.ts';
import { registerListIosHighRiskRegionsTool } from './list_ios_high_risk_regions.ts';
import { registerListIosRegionNameOptionsTool } from './list_ios_region_name_options.ts';
import { registerListUserLevelStrategiesTool } from './list_user_level_strategies.ts';
import { registerGetUserLevelNameListTool } from './get_user_level_name_list.ts';
import { registerListUserLevelsTool } from './list_user_levels.ts';
import { registerListUserLevelUsersTool } from './list_user_level_users.ts';
import { registerGetUserLevelChangeReportTool } from './get_user_level_change_report.ts';
import { registerGetUserLevelChangeReportDetailTool } from './get_user_level_change_report_detail.ts';
import { registerAddUserLevelTool } from './add_user_level.ts';
import { registerUpdateUserLevelTool } from './update_user_level.ts';
import { registerDeleteUserLevelTool } from './delete_user_level.ts';
import { registerLockUserLevelTool } from './lock_user_level.ts';
import { registerGetWorldCupInfoListTool } from './get_world_cup_info_list.ts';
import { registerGetWorldCupFixturesInfoTool } from './get_world_cup_fixtures_info.ts';
import { registerGetMilestoneRecordTool } from './get_milestone_record.ts';
import { registerGetMilestoneTotalAwardAndMilesTool } from './get_milestone_total_award_and_miles.ts';
import { registerGetGoalSprintRecordTool } from './get_goal_sprint_record.ts';
import { registerGetGoalSprintTotalAwardAndMilesTool } from './get_goal_sprint_total_award_and_miles.ts';
import { registerGetWorldCupKnockoutRecordsTool } from './get_world_cup_knockout_records.ts';
import { registerGetWorldCupKnockoutTotalAwardTool } from './get_world_cup_knockout_total_award.ts';
import { registerGetUploadWorldCupImageTokenTool } from './get_upload_world_cup_image_token.ts';
import { registerSaveWorldCupFixturesInfoTool } from './save_world_cup_fixtures_info.ts';
import { registerSaveWorldCupInfoTool } from './save_world_cup_info.ts';
import { registerListUserWageringsTool } from './list_user_wagerings.ts';
import { registerGetWageringScopesTool } from './get_wagering_scopes.ts';
import { registerGetUserUnWageringDetailTool } from './get_user_un_wagering_detail.ts';
import { registerGetManualAddUserWageringInfoTool } from './get_manual_add_user_wagering_info.ts';
import { registerGetWageringSettingTool } from './get_wagering_setting.ts';
import { registerGetTurnoverMultiplierSettingTool } from './get_turnover_multiplier_setting.ts';
import { registerListUserWageringsByUserTool } from './list_user_wagerings_by_user.ts';
import { registerGetImmediateUserWageringTool } from './get_immediate_user_wagering.ts';
import { registerUpdateTurnoverMultiplierSettingTool } from './update_turnover_multiplier_setting.ts';
import { registerUpdateWageringSettingTool } from './update_wagering_setting.ts';

export type ServerMode = 'stdio' | 'hosted';

/**
 * H7：hosted 模式停用 login tool（plan.md D4），設計理由與 admin 端逐字相同，
 * 完整說明見 obsidian/mcps/aladdin-admin/src/tools/index.ts 同一段註解。
 */
export function registerPlatformTools(server: McpServer, mode: ServerMode = 'stdio'): void {
    if (mode === 'stdio') {
        registerLoginTool(server);
    }
    registerListGameVendorsTool(server);
    registerListVendorGamesTool(server);
    registerOnboardVendorGameTool(server);
    registerGetMessageBoardSettingTool(server);
    registerUpdateMessageBoardSettingTool(server);
    registerGetMessageBoardPostsTool(server);
    registerGetPostCommentsTool(server);
    registerGetPostGiftRecordsTool(server);
    registerGetMessageBoardCommentsTool(server);
    registerReviewPostTool(server);
    registerBatchReviewPostsTool(server);
    registerDelistPostTool(server);
    registerRelistPostTool(server);
    registerSetIsPinnedPostTool(server);
    registerRemovePostTool(server);
    registerGetGameLocalizationsTool(server);
    registerListTwoEightGamesTool(server);
    registerListInHouseVendorsTool(server);
    registerGetGameVendorTool(server);
    registerUpdateGameVendorTool(server);
    registerResolveInHousePlayGroupGameIdsTool(server);
    registerUpdateGameVendorStatusTool(server);
    registerGetActivityTabsTool(server);
    registerCreateOrUpdateActivityTabTool(server);
    registerToggleActivityTabTool(server);
    registerGetActivityConfigsTool(server);
    registerGetUserIdByIdentifierTool(server);
    registerGetFissionActivityOptionsTool(server);
    registerListHomePagePopupsTool(server);
    registerCreateHomePagePopupTool(server);
    registerSetHomePagePopupStatusTool(server);
    registerEditHomePagePopupTool(server);
    registerListHomePagePopupFissionActivitiesTool(server);
    registerListFloatingWindowsTool(server);
    registerCreateFloatingWindowTool(server);
    registerUpdateRoomSortOrderTool(server);
    registerGetMuteHistoryTool(server);
    registerCreateOrUpdateRoomMuteTool(server);
    registerUpdateGameVendorMaintenanceStatusTool(server);
    registerUpdateGameVendorGameStatusTool(server);
    registerListAllBrandsTool(server);
    registerGetBrandForEditTool(server);
    registerUpdateBrandStatusTool(server);
    registerListAllGameDisplayTagsTool(server);
    registerUpdateGameTagStatusTool(server);
    registerUpdateGameTagSortOrderTool(server);
    registerCreateOrUpdateGameDisplayTagTool(server);
    registerListCustomerCategoryDetailsTool(server);
    registerUpdateCustomerCategorySortOrderTool(server);
    registerUpdateCustomerCategoryStatusTool(server);
    registerGetCustomerConfigRestrictTool(server);
    registerSetCustomerConfigRestrictTool(server);
    registerGetCustomerTicketsTool(server);
    registerCreateOrUpdateItemTool(server);
    registerListItemsTool(server);
    registerListEnabledItemsAllTool(server);
    registerGetItemNamesByIdTool(server);
    registerUpdateItemStatusTool(server);
    registerListRoomsTool(server);
    registerGetRoomNamesTool(server);
    registerGetRoomAnnouncementsTool(server);
    registerGetRoomMembersTool(server);
    registerGetMutedRoomMembersTool(server);
    registerKickRoomMemberTool(server);
    registerMuteRoomMemberTool(server);
    registerUnmuteRoomMemberTool(server);
    registerGetRoomChatHistoryTool(server);
    registerGetRoomChatRecordsTool(server);
    registerGetRoomShowOrderRecordsTool(server);
    registerGetRoomMonitorListTool(server);
    registerGetRoomMuteListTool(server);
    registerGetPlatformModulesTool(server);
    registerListPointTransactionsTool(server);
    registerListAppUserTotalPointsTool(server);
    registerListVipPointSettingsTool(server);
    registerGetPointSettingTool(server);
    registerUpdatePointSettingTool(server);
    registerGetVipPointSettingTool(server);
    registerUpdateVipPointSettingTool(server);
    registerGetPointSignInSettingTool(server);
    registerUpdatePointSignInSettingTool(server);
    registerGetPointHolidaySettingTool(server);
    registerUpdatePointHolidayStatusTool(server);
    registerCreateOrUpdatePointHolidayBonusTool(server);
    registerDeletePointHolidayBonusTool(server);
    registerGetVipSettingEquityIconsTool(server);
    registerGetVipLevelSettingsTool(server);
    registerDeleteVipLevelSettingTool(server);
    registerGetVipSettingTool(server);
    registerUpdateVipSettingTool(server);
    registerGetChatSpeechSettingTool(server);
    registerUpdateChatSpeechSettingTool(server);
    registerGetPlatformVerificationConfigTool(server);
    registerUpdatePlatformVerificationCaptchaTypeTool(server);
    registerListInformationConfigsTool(server);
    registerGetInformationReadCountTool(server);
    registerCreateUrgentInfoConfigTool(server);
    registerListPlatformRiskStrategiesTool(server);
    registerGetPlatformRiskStrategiesTool(server);
    registerGetPlatformRiskStrategyForEditTool(server);
    registerUpdatePlatformRiskStrategyStatusTool(server);
    registerListPlatformRiskEventsTool(server);
    registerGetIpRegionListTool(server);
    registerCreateOrUpdateIpRegionTool(server);
    registerUpdateIpRegionStatusTool(server);
    registerBatchUpdateIpRegionStatusTool(server);
    registerDeleteIpRegionTool(server);
    registerBatchDeleteIpRegionTool(server);
    registerGetInHouseVendorListTool(server);
    registerGetInHousePlayGroupListTool(server);
    registerGetShowCategoryTool(server);
    registerUpdateShowCategoryTool(server);
    registerListClassificationCategoriesTool(server);
    registerCreateOrUpdateClassificationTool(server);
    registerDeleteClassificationTool(server);
    registerGetCategoriesByClassificationTool(server);
    registerListUserTransactionsTool(server);
    registerGetAuditLogsTool(server);
    registerListRoomGiftsTool(server);
    registerGetRoomGiftStatisticSummaryTool(server);
    registerListRecordsTool(server);
    registerGetAnchorStatisticSummaryTool(server);
    registerGetPlatformStatisticSummaryTool(server);
    registerGetCurrenciesTool(server);
    registerUpdateCurrencyStatusTool(server);
    registerGetOtpSmsSettingsTool(server);
    registerUpdateOtpSmsSettingsTool(server);
    registerGetRegistrationIpQuotaConfigTool(server);
    registerUpdateRegistrationIpQuotaConfigTool(server);
    registerListRegistrationIpQuotasTool(server);
    registerExportRegistrationIpQuotasTool(server);
    registerToggleRegistrationIpQuotaStatusTool(server);
    registerReleaseRegistrationIpQuotaTool(server);
    registerListRegistrationIpUsersTool(server);
    registerGetUserEnterHistoryAppDomainsTool(server);
    registerGetUserEnterHistoryDomainReportTool(server);
    registerGetUserEnterHistoryDeviceReportTool(server);
    registerGetRegistrationFieldConfigsTool(server);
    registerCreateOrUpdateRegistrationFieldConfigTool(server);
    registerGetRegistrationLimitConfigTool(server);
    registerUpdateRegistrationLimitConfigTool(server);
    registerGetLoginRulesTool(server);
    registerUpdateLoginPromptConfigTool(server);
    registerUpdateLoginVerificationConfigTool(server);
    registerUpdatePasswordResetConfigTool(server);
    registerListTradePasswordLockRecordTool(server);
    registerUnlockTradePasswordLockRecordTool(server);
    registerGetTradePasswordLockConfigTool(server);
    registerCreateOrUpdateTradePasswordLockConfigTool(server);
    registerGetFreezeConfigTool(server);
    registerUpdateFreezeConfigTool(server);
    registerGetAgentPhoneNumberVisibilityTool(server);
    registerViewAgentPhoneNumberTool(server);
    registerListAgentReportsTool(server);
    registerListAgentReportDetailsTool(server);
    registerGetAgentReportStatisticsTool(server);
    registerListAgentGameReportsTool(server);
    registerListAgentBetRecordsTool(server);
    registerListAgentMemberGameReportsTool(server);
    registerListAgentLoginHistoriesTool(server);
    registerListAgentReferralDomainsTool(server);
    registerGetDailyPaymentHighNetWorthStatisticsTool(server);
    registerGetDailyPaymentHighNetWorthUsersTool(server);
    registerGetDailyUserGameVendorTagBetSummaryTool(server);
    registerGetDailyUserGameVendorTagBetUserSummaryTool(server);
    registerGetTodayPlatformStatisticTool(server);
    registerGetYesterdayPlatformStatisticTool(server);
    registerListDailyVipStatisticsTool(server);
    registerListDepositMethodStatisticsTool(server);
    registerListDepositDailyReportTool(server);
    registerListDepositWithdrawDailyReportTool(server);
    registerGetSupportedLanguagesTool(server);
    registerGetTimezoneTool(server);
    registerGetPlatformCodeTool(server);
    registerListUsersTool(server);
    registerUpdateUserStatusTool(server);
    registerListPlatformSupportedLanguagesTool(server);
    registerCreateOrUpdateSupportLanguageTool(server);
    registerGetBackofficeSupportedLanguagesTool(server);
    registerToggleBackofficeLanguageStatusTool(server);
    registerSetBackofficeDefaultLanguageTool(server);
    registerGetPlatformIdRolesTool(server);
    registerNewUserTool(server);
    registerListActivityRankingSettingsTool(server);
    registerGetPlatformRankingActivityListTool(server);
    registerChangeActivityRankingSettingStatusTool(server);
    registerCreateOrUpdateActivityRankingSettingTool(server);
    registerListFixedRankingSettingsTool(server);
    registerChangeFixedRankingStatusTool(server);
    registerUpdateFixedRankingSettingTool(server);
    registerListFixedRankingEntriesTool(server);
    registerGetRouletteConfigNameListTool(server);
    registerGetRouletteConfigListTool(server);
    registerGetRouletteConfigByIdTool(server);
    registerSwitchRouletteConfigStatusTool(server);
    registerGetRouletteRewardListTool(server);
    registerGetRouletteRewardByIdTool(server);
    registerGetRouletteRecordListTool(server);
    registerCreateOrUpdateRouletteConfigTool(server);
    registerCreateOrUpdateRouletteRewardTool(server);
    registerGetSensitiveWordsTool(server);
    registerCreateOrUpdateSensitiveWordTool(server);
    registerBatchRemoveSensitiveWordTool(server);
    registerGetRouletteRewardNameListTool(server);
    registerGetLiveTabsTool(server);
    registerCreateOrUpdateLiveTabTool(server);
    registerUpdateLiveTabStatusTool(server);
    registerGetLiveCategoriesTool(server);
    registerCreateOrUpdateLiveCategoryTool(server);
    registerUpdateLiveCategoryStatusTool(server);
    registerGetMerchantListTool(server);
    registerToggleMerchantStatusTool(server);
    registerGetMerchantSettingTool(server);
    registerEditMerchantSettingTool(server);
    registerListAppGroupsTool(server);
    registerListAppsTool(server);
    registerUpdateAppTool(server);
    registerListAppVersionsTool(server);
    registerGetAppVersionForEditTool(server);
    registerListDownloadLinksTool(server);
    registerListIosHighRiskRegionsTool(server);
    registerListIosRegionNameOptionsTool(server);
    registerListUserLevelStrategiesTool(server);
    registerGetUserLevelNameListTool(server);
    registerListUserLevelsTool(server);
    registerListUserLevelUsersTool(server);
    registerGetUserLevelChangeReportTool(server);
    registerGetUserLevelChangeReportDetailTool(server);
    registerAddUserLevelTool(server);
    registerUpdateUserLevelTool(server);
    registerDeleteUserLevelTool(server);
    registerLockUserLevelTool(server);
    registerGetWorldCupInfoListTool(server);
    registerGetWorldCupFixturesInfoTool(server);
    registerGetMilestoneRecordTool(server);
    registerGetMilestoneTotalAwardAndMilesTool(server);
    registerGetGoalSprintRecordTool(server);
    registerGetGoalSprintTotalAwardAndMilesTool(server);
    registerGetWorldCupKnockoutRecordsTool(server);
    registerGetWorldCupKnockoutTotalAwardTool(server);
    registerGetUploadWorldCupImageTokenTool(server);
    registerSaveWorldCupFixturesInfoTool(server);
    registerSaveWorldCupInfoTool(server);
    registerListUserWageringsTool(server);
    registerGetWageringScopesTool(server);
    registerGetUserUnWageringDetailTool(server);
    registerGetManualAddUserWageringInfoTool(server);
    registerGetWageringSettingTool(server);
    registerGetTurnoverMultiplierSettingTool(server);
    registerListUserWageringsByUserTool(server);
    registerGetImmediateUserWageringTool(server);
    registerUpdateTurnoverMultiplierSettingTool(server);
    registerUpdateWageringSettingTool(server);
}
