/**
 * tools/index.ts — 把所有 tool 註冊函式掛到同一個 McpServer 實例。
 * 純聚合層，不放任何業務邏輯。
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerLoginTool } from './login.ts';
import { registerListGameVendorsTool } from './list_game_vendors.ts';
import { registerListVendorGamesTool } from './list_vendor_games.ts';
import { registerOnboardVendorGameTool } from './onboard_vendor_game.ts';
import { registerGetMessageBoardSettingTool } from './get_message_board_setting.ts';
import { registerUpdateMessageBoardSettingTool } from './update_message_board_setting.ts';
import { registerGetMessageBoardPostsTool } from './get_message_board_posts.ts';
import { registerGetPostCommentsTool } from './get_post_comments.ts';
import { registerGetPostGiftRecordsTool } from './get_post_gift_records.ts';
import { registerGetMessageBoardCommentsTool } from './get_message_board_comments.ts';
import { registerGetGameLocalizationsTool } from './get_game_localizations.ts';
import { registerListTwoEightGamesTool } from './list_two_eight_games.ts';
import { registerListInHouseVendorsTool } from './list_in_house_vendors.ts';
import { registerGetGameVendorTool } from './get_game_vendor.ts';
import { registerUpdateGameVendorTool } from './update_game_vendor.ts';
import { registerResolveInHousePlayGroupGameIdsTool } from './resolve_in_house_play_group_game_ids.ts';
import { registerUpdateGameVendorStatusTool } from './update_game_vendor_status.ts';
import { registerGetActivityTabsTool } from './get_activity_tabs.ts';
import { registerCreateOrUpdateActivityTabTool } from './create_or_update_activity_tab.ts';
import { registerToggleActivityTabTool } from './toggle_activity_tab.ts';
import { registerGetActivityConfigsTool } from './get_activity_configs.ts';
import { registerGetUserIdByIdentifierTool } from './get_user_id_by_identifier.ts';
import { registerGetFissionActivityOptionsTool } from './get_fission_activity_options.ts';
import { registerListHomePagePopupsTool } from './list_home_page_popups.ts';
import { registerCreateHomePagePopupTool } from './create_home_page_popup.ts';
import { registerSetHomePagePopupStatusTool } from './set_home_page_popup_status.ts';
import { registerEditHomePagePopupTool } from './edit_home_page_popup.ts';
import { registerListHomePagePopupFissionActivitiesTool } from './list_home_page_popup_fission_activities.ts';
import { registerListFloatingWindowsTool } from './list_floating_windows.ts';
import { registerCreateFloatingWindowTool } from './create_floating_window.ts';
import { registerUpdateRoomSortOrderTool } from './update_room_sort_order.ts';
import { registerGetMuteHistoryTool } from './get_mute_history.ts';
import { registerCreateOrUpdateRoomMuteTool } from './create_or_update_room_mute.ts';
import { registerUpdateGameVendorMaintenanceStatusTool } from './update_game_vendor_maintenance_status.ts';
import { registerUpdateGameVendorGameStatusTool } from './update_game_vendor_game_status.ts';
import { registerListAllBrandsTool } from './list_all_brands.ts';
import { registerGetBrandForEditTool } from './get_brand_for_edit.ts';
import { registerUpdateBrandStatusTool } from './update_brand_status.ts';
import { registerListAllGameDisplayTagsTool } from './list_all_game_display_tags.ts';
import { registerUpdateGameTagStatusTool } from './update_game_tag_status.ts';
import { registerUpdateGameTagSortOrderTool } from './update_game_tag_sort_order.ts';
import { registerCreateOrUpdateGameDisplayTagTool } from './create_or_update_game_display_tag.ts';
import { registerListCustomerCategoryDetailsTool } from './list_customer_category_details.ts';
import { registerUpdateCustomerCategorySortOrderTool } from './update_customer_category_sort_order.ts';
import { registerUpdateCustomerCategoryStatusTool } from './update_customer_category_status.ts';
import { registerGetCustomerConfigRestrictTool } from './get_customer_config_restrict.ts';
import { registerSetCustomerConfigRestrictTool } from './set_customer_config_restrict.ts';
import { registerGetCustomerTicketsTool } from './get_customer_tickets.ts';
import { registerCreateOrUpdateItemTool } from './create_or_update_item.ts';
import { registerListItemsTool } from './list_items.ts';
import { registerListEnabledItemsAllTool } from './list_enabled_items_all.ts';
import { registerGetItemNamesByIdTool } from './get_item_names_by_id.ts';
import { registerUpdateItemStatusTool } from './update_item_status.ts';
import { registerListRoomsTool } from './list_rooms.ts';
import { registerGetRoomNamesTool } from './get_room_names.ts';
import { registerGetRoomAnnouncementsTool } from './get_room_announcements.ts';
import { registerGetRoomMembersTool } from './get_room_members.ts';
import { registerGetMutedRoomMembersTool } from './get_muted_room_members.ts';
import { registerKickRoomMemberTool } from './kick_room_member.ts';
import { registerMuteRoomMemberTool } from './mute_room_member.ts';
import { registerUnmuteRoomMemberTool } from './unmute_room_member.ts';
import { registerGetRoomChatHistoryTool } from './get_room_chat_history.ts';
import { registerGetRoomChatRecordsTool } from './get_room_chat_records.ts';
import { registerGetRoomShowOrderRecordsTool } from './get_room_show_order_records.ts';
import { registerGetRoomMonitorListTool } from './get_room_monitor_list.ts';
import { registerGetRoomMuteListTool } from './get_room_mute_list.ts';
import { registerGetPlatformModulesTool } from './get_platform_modules.ts';
import { registerListPointTransactionsTool } from './list_point_transactions.ts';
import { registerListAppUserTotalPointsTool } from './list_app_user_total_points.ts';
import { registerListVipPointSettingsTool } from './list_vip_point_settings.ts';
import { registerGetPointSettingTool } from './get_point_setting.ts';
import { registerUpdatePointSettingTool } from './update_point_setting.ts';
import { registerGetVipPointSettingTool } from './get_vip_point_setting.ts';
import { registerUpdateVipPointSettingTool } from './update_vip_point_setting.ts';
import { registerGetPointSignInSettingTool } from './get_point_sign_in_setting.ts';
import { registerUpdatePointSignInSettingTool } from './update_point_sign_in_setting.ts';
import { registerGetPointHolidaySettingTool } from './get_point_holiday_setting.ts';
import { registerUpdatePointHolidayStatusTool } from './update_point_holiday_status.ts';
import { registerCreateOrUpdatePointHolidayBonusTool } from './create_or_update_point_holiday_bonus.ts';
import { registerDeletePointHolidayBonusTool } from './delete_point_holiday_bonus.ts';
import { registerGetVipSettingEquityIconsTool } from './get_vip_setting_equity_icons.ts';
import { registerGetVipLevelSettingsTool } from './get_vip_level_settings.ts';
import { registerDeleteVipLevelSettingTool } from './delete_vip_level_setting.ts';
import { registerGetVipSettingTool } from './get_vip_setting.ts';
import { registerUpdateVipSettingTool } from './update_vip_setting.ts';
import { registerGetChatSpeechSettingTool } from './get_chat_speech_setting.ts';
import { registerUpdateChatSpeechSettingTool } from './update_chat_speech_setting.ts';
import { registerGetPlatformVerificationConfigTool } from './get_platform_verification_config.ts';
import { registerUpdatePlatformVerificationCaptchaTypeTool } from './update_platform_verification_captcha_type.ts';
import { registerListInformationConfigsTool } from './list_information_configs.ts';
import { registerGetInformationReadCountTool } from './get_information_read_count.ts';
import { registerCreateUrgentInfoConfigTool } from './create_urgent_info_config.ts';
import { registerListPlatformRiskStrategiesTool } from './list_platform_risk_strategies.ts';
import { registerGetPlatformRiskStrategiesTool } from './get_platform_risk_strategies.ts';
import { registerGetPlatformRiskStrategyForEditTool } from './get_platform_risk_strategy_for_edit.ts';
import { registerUpdatePlatformRiskStrategyStatusTool } from './update_platform_risk_strategy_status.ts';
import { registerListPlatformRiskEventsTool } from './list_platform_risk_events.ts';
import { registerGetIpRegionListTool } from './get_ip_region_list.ts';
import { registerCreateOrUpdateIpRegionTool } from './create_or_update_ip_region.ts';
import { registerUpdateIpRegionStatusTool } from './update_ip_region_status.ts';
import { registerBatchUpdateIpRegionStatusTool } from './batch_update_ip_region_status.ts';
import { registerDeleteIpRegionTool } from './delete_ip_region.ts';
import { registerBatchDeleteIpRegionTool } from './batch_delete_ip_region.ts';
import { registerGetInHouseVendorListTool } from './get_in_house_vendor_list.ts';
import { registerGetInHousePlayGroupListTool } from './get_in_house_play_group_list.ts';
import { registerGetShowCategoryTool } from './get_show_category.ts';
import { registerUpdateShowCategoryTool } from './update_show_category.ts';
import { registerListClassificationCategoriesTool } from './list_classification_categories.ts';
import { registerCreateOrUpdateClassificationTool } from './create_or_update_classification.ts';
import { registerDeleteClassificationTool } from './delete_classification.ts';
import { registerGetCategoriesByClassificationTool } from './get_categories_by_classification.ts';
import { registerListUserTransactionsTool } from './list_user_transactions.ts';
import { registerGetAuditLogsTool } from './get_audit_logs.ts';
import { registerListRoomGiftsTool } from './list_room_gifts.ts';
import { registerGetRoomGiftStatisticSummaryTool } from './get_room_gift_statistic_summary.ts';
import { registerListRecordsTool } from './list_records.ts';
import { registerGetAnchorStatisticSummaryTool } from './get_anchor_statistic_summary.ts';
import { registerGetPlatformStatisticSummaryTool } from './get_platform_statistic_summary.ts';
import { registerGetCurrenciesTool } from './get_currencies.ts';
import { registerUpdateCurrencyStatusTool } from './update_currency_status.ts';
import { registerGetOtpSmsSettingsTool } from './get_otp_sms_settings.ts';
import { registerUpdateOtpSmsSettingsTool } from './update_otp_sms_settings.ts';

export type ServerMode = 'stdio' | 'hosted';

/**
 * H7：hosted 模式停用 login tool（plan.md D4），設計理由與 admin 端逐字相同，
 * 完整說明見 obsidian/mcps/aladdin-admin/src/tools/index.ts 同一段註解。
 */
export function registerPlatformTools(server: McpServer, mode: ServerMode = 'stdio'): void {
    if (mode === 'stdio') {
        registerLoginTool(server);
    }
    registerListGameVendorsTool(server);
    registerListVendorGamesTool(server);
    registerOnboardVendorGameTool(server);
    registerGetMessageBoardSettingTool(server);
    registerUpdateMessageBoardSettingTool(server);
    registerGetMessageBoardPostsTool(server);
    registerGetPostCommentsTool(server);
    registerGetPostGiftRecordsTool(server);
    registerGetMessageBoardCommentsTool(server);
    registerGetGameLocalizationsTool(server);
    registerListTwoEightGamesTool(server);
    registerListInHouseVendorsTool(server);
    registerGetGameVendorTool(server);
    registerUpdateGameVendorTool(server);
    registerResolveInHousePlayGroupGameIdsTool(server);
    registerUpdateGameVendorStatusTool(server);
    registerGetActivityTabsTool(server);
    registerCreateOrUpdateActivityTabTool(server);
    registerToggleActivityTabTool(server);
    registerGetActivityConfigsTool(server);
    registerGetUserIdByIdentifierTool(server);
    registerGetFissionActivityOptionsTool(server);
    registerListHomePagePopupsTool(server);
    registerCreateHomePagePopupTool(server);
    registerSetHomePagePopupStatusTool(server);
    registerEditHomePagePopupTool(server);
    registerListHomePagePopupFissionActivitiesTool(server);
    registerListFloatingWindowsTool(server);
    registerCreateFloatingWindowTool(server);
    registerUpdateRoomSortOrderTool(server);
    registerGetMuteHistoryTool(server);
    registerCreateOrUpdateRoomMuteTool(server);
    registerUpdateGameVendorMaintenanceStatusTool(server);
    registerUpdateGameVendorGameStatusTool(server);
    registerListAllBrandsTool(server);
    registerGetBrandForEditTool(server);
    registerUpdateBrandStatusTool(server);
    registerListAllGameDisplayTagsTool(server);
    registerUpdateGameTagStatusTool(server);
    registerUpdateGameTagSortOrderTool(server);
    registerCreateOrUpdateGameDisplayTagTool(server);
    registerListCustomerCategoryDetailsTool(server);
    registerUpdateCustomerCategorySortOrderTool(server);
    registerUpdateCustomerCategoryStatusTool(server);
    registerGetCustomerConfigRestrictTool(server);
    registerSetCustomerConfigRestrictTool(server);
    registerGetCustomerTicketsTool(server);
    registerCreateOrUpdateItemTool(server);
    registerListItemsTool(server);
    registerListEnabledItemsAllTool(server);
    registerGetItemNamesByIdTool(server);
    registerUpdateItemStatusTool(server);
    registerListRoomsTool(server);
    registerGetRoomNamesTool(server);
    registerGetRoomAnnouncementsTool(server);
    registerGetRoomMembersTool(server);
    registerGetMutedRoomMembersTool(server);
    registerKickRoomMemberTool(server);
    registerMuteRoomMemberTool(server);
    registerUnmuteRoomMemberTool(server);
    registerGetRoomChatHistoryTool(server);
    registerGetRoomChatRecordsTool(server);
    registerGetRoomShowOrderRecordsTool(server);
    registerGetRoomMonitorListTool(server);
    registerGetRoomMuteListTool(server);
    registerGetPlatformModulesTool(server);
    registerListPointTransactionsTool(server);
    registerListAppUserTotalPointsTool(server);
    registerListVipPointSettingsTool(server);
    registerGetPointSettingTool(server);
    registerUpdatePointSettingTool(server);
    registerGetVipPointSettingTool(server);
    registerUpdateVipPointSettingTool(server);
    registerGetPointSignInSettingTool(server);
    registerUpdatePointSignInSettingTool(server);
    registerGetPointHolidaySettingTool(server);
    registerUpdatePointHolidayStatusTool(server);
    registerCreateOrUpdatePointHolidayBonusTool(server);
    registerDeletePointHolidayBonusTool(server);
    registerGetVipSettingEquityIconsTool(server);
    registerGetVipLevelSettingsTool(server);
    registerDeleteVipLevelSettingTool(server);
    registerGetVipSettingTool(server);
    registerUpdateVipSettingTool(server);
    registerGetChatSpeechSettingTool(server);
    registerUpdateChatSpeechSettingTool(server);
    registerGetPlatformVerificationConfigTool(server);
    registerUpdatePlatformVerificationCaptchaTypeTool(server);
    registerListInformationConfigsTool(server);
    registerGetInformationReadCountTool(server);
    registerCreateUrgentInfoConfigTool(server);
    registerListPlatformRiskStrategiesTool(server);
    registerGetPlatformRiskStrategiesTool(server);
    registerGetPlatformRiskStrategyForEditTool(server);
    registerUpdatePlatformRiskStrategyStatusTool(server);
    registerListPlatformRiskEventsTool(server);
    registerGetIpRegionListTool(server);
    registerCreateOrUpdateIpRegionTool(server);
    registerUpdateIpRegionStatusTool(server);
    registerBatchUpdateIpRegionStatusTool(server);
    registerDeleteIpRegionTool(server);
    registerBatchDeleteIpRegionTool(server);
    registerGetInHouseVendorListTool(server);
    registerGetInHousePlayGroupListTool(server);
    registerGetShowCategoryTool(server);
    registerUpdateShowCategoryTool(server);
    registerListClassificationCategoriesTool(server);
    registerCreateOrUpdateClassificationTool(server);
    registerDeleteClassificationTool(server);
    registerGetCategoriesByClassificationTool(server);
    registerListUserTransactionsTool(server);
    registerGetAuditLogsTool(server);
    registerListRoomGiftsTool(server);
    registerGetRoomGiftStatisticSummaryTool(server);
    registerListRecordsTool(server);
    registerGetAnchorStatisticSummaryTool(server);
    registerGetPlatformStatisticSummaryTool(server);
    registerGetCurrenciesTool(server);
    registerUpdateCurrencyStatusTool(server);
    registerGetOtpSmsSettingsTool(server);
    registerUpdateOtpSmsSettingsTool(server);
}
